#!/bin/python3

import sys

def aVeryBigSum(n, ar):
    # Complete this function
    bigsum = sum(int(arr_temp) for arr_temp in ar)
    
    return bigsum

n = int(input().strip())
ar = list(map(int, input().strip().split(' ')))
result = aVeryBigSum(n, ar)
print(result)
