#!/bin/python3

import sys

def solve(a0, a1, a2, b0, b1, b2):
    # Complete this function
    a_triplet = a0, a1, a2
    b_triplet = b0, b1, b2
    alice, bob = 0, 0

    for a_val, b_val in zip(a_triplet, b_triplet):
        if a_val < b_val:
            bob += 1
        elif a_val > b_val:
            alice += 1
    
    return alice, bob

a0, a1, a2 = input().strip().split(' ')
a0, a1, a2 = [int(a0), int(a1), int(a2)]
b0, b1, b2 = input().strip().split(' ')
b0, b1, b2 = [int(b0), int(b1), int(b2)]
result = solve(a0, a1, a2, b0, b1, b2)
print (" ".join(map(str, result)))
