#!/bin/python3

import sys

n = int(input().strip())
arr = [int(arr_temp) for arr_temp in input().strip().split(' ')]

pos, neg, zero = 0,0,0

for i in arr  :
    if i > 0 :
        pos += 1
    elif i < 0 :
        neg += 1
    else :
        zero += 1

pos_ratio = pos / n
neg_ratio = neg / n
zero_ratio = zero / n

print(pos_ratio)
print(neg_ratio)
print(zero_ratio)
